spring:
  application:
    name: listener-demo

  cloud:
    # Consul
    consul:
      host: 127.0.0.1
      port: 8500

server:
  port: 18080 # 随机端口，方便启动多个消费者

management:
  endpoints:
    # Actuator HTTP 配置项，对应 WebEndpointProperties 配置类
    web:
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
